### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by valkyrienyanko** [GodotModules/GodotModulesCSharp#124]
### v0.2
- [ ] Inventory UI
- [ ] Weapons (swords, staffs, bows, guns) with visible modifiers / different weapon variations
- [ ] Enemy movement / interesting combat

### v0.3
- [ ] Getting netcode up and running
- [ ] Lobby netcode
- [ ] Game netcode for all of mechanics from v0.2
