### ISSUE TITLE
Todo Checklist

### ISSUE THREAD

**Issue by valkyrienyanko** [GodotModules/GodotModulesCSharp#14]
> ⚠️ **IMPORTANT**: This list is outdated, please contact valk through the Discord to learn more on what needs to be done.

# High Priority
### Netcode
- [ ] Bullets
- [ ] Enemies

# Low Priority
### ModLoader
- [ ] Add button to activate debug server (also add try catch to warn user only one debug server on one client can be running at a time)

### Master NodeJS Server
- [ ] Add modding documentation to public/index.html
- [ ] Add button "Send Bug Report" to error popups which will spawn a send bug report window popup with the most recent error (also add a way to access this popup from the menus)

### Netcode
- [ ] Change lobby name while lobby is created already
- [ ] Host can ban players
- [ ] Server mods
- [ ] Server checks if client has the right mods (add required mods list server owners can populate)

**Comment by LazerGoat** [comment]
Suggestion for end of netcode todo list? : modded assets mismatch checker in multiplayer servers. Basically checking if joining client has the same mods as the server before allowing their connection. ( if mods were intended to work on servers to begin with )

**Comment by valkyrienyanko** [comment]
That's a good idea. I'm not 100% sure how server mods will work as I've only got mods working for the client. I'd imagine I would just create a Lua table for Server and link methods like Server:Kick(string playerName). Maybe if I look at some examples at server side mods from other games I'll get a better idea of what needs to be done.

The master server would need to have a list of mods for each server listing as well.

I will add this to the todo list.

**Comment by LazerGoat** [comment]
> The master server would need to have a list of mods for each server listing as well.

Yeah I was thinking of the server as an instance with a mods folder, that would have to be respected by the client if assets mismatched is disabled in the server config for example. This could be part of a larger server config later, could even be put in a json file at some point

**Comment by valkyrienyanko** [comment]
That is above me right now. I think once the netcode game demo starts getting developed the server mods / mod checks will become more clear on what needs to be done.
